<html>
<head>
<title>Error and Exception Handling in Python: Fundamentals for Data Scientists</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Python 中的错误和异常处理:数据科学家基础</h1>
<blockquote>原文：<a href="https://towardsdatascience.com/error-and-exception-handling-in-python-fundamentals-for-data-scientists-4b349256d16d?source=collection_archive---------10-----------------------#2020-07-17">https://towardsdatascience.com/error-and-exception-handling-in-python-fundamentals-for-data-scientists-4b349256d16d?source=collection_archive---------10-----------------------#2020-07-17</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><div class=""/><div class=""><h2 id="207d" class="pw-subtitle-paragraph jq is it bd b jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh dk translated">用一个具体的例子来理解基础！</h2></div><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi ki"><img src="../Images/05c08a7ef44dc1e1ee8d3610246a7add.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*zH1qDdDfmdxAY7gH"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk translated">图片由<a class="ae ky" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上的<a class="ae ky" href="https://unsplash.com/@alexacea?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Alexandru Acea </a>拍摄</p></figure><p id="f7ee" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">Python 中主要有三种可区分的错误:<strong class="lb iu">语法错误</strong>、<strong class="lb iu">异常和逻辑错误</strong>。</p><ul class=""><li id="eb33" class="lv lw it lb b lc ld lf lg li lx lm ly lq lz lu ma mb mc md bi translated"><strong class="lb iu">语法错误</strong>类似于语言中的语法或拼写错误。如果您的代码中有这样的错误，Python 就无法开始执行您的代码。您会得到一个明确的错误消息，指出什么是错误的，什么需要修复。因此，这是最容易修复的错误类型。</li><li id="1c8e" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">Python 中常见的<strong class="lb iu">语法错误</strong>有符号缺失(如逗号、括号、冒号)、关键字拼写错误、缩进不正确。</li><li id="0625" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated"><strong class="lb iu">异常</strong>可能出现在运行时语法正确的代码块中。当 Python 无法执行请求的操作时，它会终止代码并引发一条错误消息。</li><li id="cf08" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">试图从一个不存在的文件中读取数据，对不兼容类型的变量执行操作，将一个数除以零是 Python 中常见的引发错误的<strong class="lb iu">异常</strong>。</li><li id="4830" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">我们必须消除<strong class="lb iu">语法错误</strong>来运行我们的 Python 代码，而<strong class="lb iu">异常</strong>可以在运行时处理。</li><li id="a1ac" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">逻辑错误是最难修复的错误，因为它们不会让你的代码崩溃，你也不会得到任何错误消息。</li><li id="b7ad" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">如果您有逻辑错误，您的代码将不会按预期运行。</li><li id="ec87" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">使用不正确的变量名、不能正确反映算法逻辑的代码、在布尔运算符上出错将导致<strong class="lb iu">逻辑错误。</strong></li></ul><pre class="kj kk kl km gt mj mk ml mm aw mn bi"><span id="7ca3" class="mo mp it mk b gy mq mr l ms mt"><strong class="mk iu"># Syntax Error-1: Misusing the Assignment Operator<br/></strong>len("data") <strong class="mk iu">=</strong> 4<br/><strong class="mk iu">Output:<br/>  </strong>File "ErrorsAndExceptions.py", line 1<br/>    len("data") = 4<br/>SyntaxError: can't assign to function call</span><span id="5de9" class="mo mp it mk b gy mu mr l ms mt"><strong class="mk iu"># Syntax Error-2: Python Keyword Misuse<br/>fr</strong> k in range(10):<br/>    print(k)<br/><strong class="mk iu">Output:</strong><br/>  File "ErrorsAndExceptions.py", line 4<br/>    fr k in range(10):<br/>       ^<br/>SyntaxError: invalid syntax</span><span id="9cfa" class="mo mp it mk b gy mu mr l ms mt"><strong class="mk iu"># Exception-1: ZeroDivisionError</strong><br/>print (5/0)<br/><strong class="mk iu">Output:<br/></strong>Traceback (most recent call last):<br/>  File "ErrorsAndExceptions.py", line 12, in &lt;module&gt;<br/>    print (5/0)<br/>ZeroDivisionError: integer division or modulo by zero</span><span id="a320" class="mo mp it mk b gy mu mr l ms mt"><strong class="mk iu"># Exception-2: TypeError</strong><br/>print ('4' + 4)<br/><strong class="mk iu">Output:</strong><br/>Traceback (most recent call last):<br/>  File "ErrorsAndExceptions.py", line 10, in &lt;module&gt;<br/>    print ('4' + 4)<br/>TypeError: cannot concatenate 'str' and 'int' objects</span></pre><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi mv"><img src="../Images/bee8d210dd4d9e8ba961c3b3a3c80a50.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*h_AvRcR9NT-2xpdX"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk translated">Uchral Sanjaadorj 在<a class="ae ky" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄的照片</p></figure><h1 id="38d7" class="mw mp it bd mx my mz na nb nc nd ne nf jz ng ka nh kc ni kd nj kf nk kg nl nm bi translated">语法错误</h1><p id="02da" class="pw-post-body-paragraph kz la it lb b lc nn ju le lf no jx lh li np lk ll lm nq lo lp lq nr ls lt lu im bi translated">当您的代码有语法错误时，Python 会停止并通过提供代码中错误的位置和明确的错误定义来引发错误。</p><pre class="kj kk kl km gt mj mk ml mm aw mn bi"><span id="7f30" class="mo mp it mk b gy mq mr l ms mt"><strong class="mk iu"># Syntax Error-1: Misusing the Assignment Operator<br/></strong>len("data") <strong class="mk iu">=</strong> 4<br/><strong class="mk iu">Output:<br/>  </strong>File "ErrorsAndExceptions.py", line 1<br/>    len("data") = 4<br/>SyntaxError: can't assign to function call</span></pre><p id="a37e" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">您需要更正语法错误才能运行代码。</p><pre class="kj kk kl km gt mj mk ml mm aw mn bi"><span id="4e27" class="mo mp it mk b gy mq mr l ms mt">len("data") <strong class="mk iu">==</strong> 4<br/><strong class="mk iu">Output:<br/></strong>True</span></pre><h1 id="4c57" class="mw mp it bd mx my mz na nb nc nd ne nf jz ng ka nh kc ni kd nj kf nk kg nl nm bi translated">异常处理</h1><p id="47d3" class="pw-post-body-paragraph kz la it lb b lc nn ju le lf no jx lh li np lk ll lm nq lo lp lq nr ls lt lu im bi translated">异常处理的主要目的是防止潜在的故障和不受控制的停止。</p><p id="1106" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">我们可以用一个<strong class="lb iu"> try-except </strong>块来捕捉和处理一个异常:</p><ul class=""><li id="0467" class="lv lw it lb b lc ld lf lg li lx lm ly lq lz lu ma mb mc md bi translated"><strong class="lb iu"> try 块</strong>包含要监控异常的代码。</li><li id="193b" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated"><strong class="lb iu"> except 块</strong>包含特定异常发生时要做的事情。如果没有异常发生，则跳过这一部分，并结束<strong class="lb iu"> try-except 语句</strong>。</li><li id="58d5" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">如果引发的异常与<strong class="lb iu">中指定的异常匹配，则执行 except 块中的代码来处理该异常。</strong></li><li id="3ba1" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">如果没有在关键字之外的<strong class="lb iu">中指定任何类型的异常，您可以捕捉任何异常。</strong></li><li id="b0d1" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated"><strong class="lb iu">当第一个异常发生时，try 块</strong>执行终止。</li><li id="0673" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated"><strong class="lb iu"> try-except 块</strong>可能有不止一个<strong class="lb iu"> except 块</strong>来处理几种不同类型的异常。</li><li id="df6c" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">可选的<strong class="lb iu"> else 块</strong>只有在<strong class="lb iu"> try 块没有出现异常的情况下才会执行。</strong>如果出现任何异常，将不会执行 else 块。</li><li id="d63e" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">可选的<strong class="lb iu">最后块</strong>用于清理代码。这个块总是被执行。</li></ul><pre class="kj kk kl km gt mj mk ml mm aw mn bi"><span id="7013" class="mo mp it mk b gy mq mr l ms mt"><strong class="mk iu">try:</strong><br/><strong class="mk iu"> #code to monitor</strong><br/> print (5/0)</span><span id="0d6b" class="mo mp it mk b gy mu mr l ms mt"><strong class="mk iu">#this code will not be executed<br/> #as above line raises a ZeroDivisionError</strong><br/> print ("this code will not be executed")</span><span id="66d0" class="mo mp it mk b gy mu mr l ms mt"><strong class="mk iu">except </strong><em class="ns">ZeroDivisionError</em> as e:<strong class="mk iu"><br/> #code to handle the exception when it occurs</strong><br/> print(e)<br/> print("OPPS")</span><span id="45a8" class="mo mp it mk b gy mu mr l ms mt"><strong class="mk iu">else:</strong><br/> print("try block executed if there is no error")</span><span id="6ec9" class="mo mp it mk b gy mu mr l ms mt"><strong class="mk iu">finally:</strong><br/> print("finally block is always executed")</span><span id="226b" class="mo mp it mk b gy mu mr l ms mt"><strong class="mk iu">Output:<br/></strong>integer division or modulo by zero<br/>OPPS<br/>finally block is always executed</span></pre><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi nt"><img src="../Images/269f65f0d6caf3f10b673fe499325833.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*XKmgB_DWKLQ5d5YZ"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk translated">照片由<a class="ae ky" href="https://unsplash.com/@mundane?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Serenity Mitchell </a>在<a class="ae ky" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄</p></figure><h1 id="031d" class="mw mp it bd mx my mz na nb nc nd ne nf jz ng ka nh kc ni kd nj kf nk kg nl nm bi translated">引发异常</h1><p id="a92b" class="pw-post-body-paragraph kz la it lb b lc nn ju le lf no jx lh li np lk ll lm nq lo lp lq nr ls lt lu im bi translated">如果特定条件发生，您可以使用<strong class="lb iu"> raise </strong>关键字手动引发异常。</p><pre class="kj kk kl km gt mj mk ml mm aw mn bi"><span id="0191" class="mo mp it mk b gy mq mr l ms mt">student_age = -4</span><span id="134d" class="mo mp it mk b gy mu mr l ms mt">if student_age &lt; 2:<br/> <strong class="mk iu">raise</strong> <em class="ns">Exception</em>("Sorry, student age cannot be lower than 2")</span><span id="2335" class="mo mp it mk b gy mu mr l ms mt"><strong class="mk iu">Output:<br/></strong>Traceback (most recent call last):<br/>  File "ErrorsAndExceptions.py", line 49, in &lt;module&gt;<br/>    raise Exception("Sorry, student age cannot be lower than 2")<br/>Exception: Sorry, student age cannot be lower than 2</span></pre><h1 id="fa17" class="mw mp it bd mx my mz na nb nc nd ne nf jz ng ka nh kc ni kd nj kf nk kg nl nm bi translated">定义自定义例外</h1><p id="a76a" class="pw-post-body-paragraph kz la it lb b lc nn ju le lf no jx lh li np lk ll lm nq lo lp lq nr ls lt lu im bi translated">如果我们希望对特定条件下发生的事情有更多的控制，我们可以定义自己的异常类型。</p><p id="bf0e" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">为此，我们从<strong class="lb iu">异常</strong>类继承。</p><pre class="kj kk kl km gt mj mk ml mm aw mn bi"><span id="ca0a" class="mo mp it mk b gy mq mr l ms mt"><em class="ns">class</em> <strong class="mk iu">InvalidStudentAgeException(<em class="ns">Exception</em>)</strong>:</span><span id="6cb8" class="mo mp it mk b gy mu mr l ms mt"><strong class="mk iu">"""Exception for errors in the student age<br/>  Attributes:<br/>  student_age -- student_age that we monitor<br/>  error_message -- explanation of the error<br/> """</strong></span><span id="a127" class="mo mp it mk b gy mu mr l ms mt"><em class="ns">def</em> <strong class="mk iu">__init__</strong>(<em class="ns">self</em>, <em class="ns">student_age</em>, error_<em class="ns">message</em>="Student age should <br/> be in 2-10 range"):</span><span id="0045" class="mo mp it mk b gy mu mr l ms mt">self.student_age = student_age<br/> self.error_message = error_message<br/> <em class="ns">super</em>().__init__(self.error_message)</span><span id="2b90" class="mo mp it mk b gy mu mr l ms mt">student_age = <em class="ns">int</em>(input("Enter Student age: "))</span><span id="a2c6" class="mo mp it mk b gy mu mr l ms mt">if not 1 &lt; student_age &lt; 11:<br/> raise <strong class="mk iu">InvalidStudentAgeException(student_age)</strong></span><span id="b49a" class="mo mp it mk b gy mu mr l ms mt"><strong class="mk iu">Output:</strong><br/>Enter Student age: 54<br/>Traceback (most recent call last):<br/>  File "ErrorsAndExceptions.py", line 68, in &lt;module&gt;<br/>    raise InvalidStudentAgeException(student_age)<br/>__main__.InvalidStudentAgeException: Student age should be in 2-10 range: 54 is not a valid age</span></pre><p id="b6e6" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">上面，我们覆盖了<strong class="lb iu">异常</strong>基类的构造函数，以使用我们自己的自定义参数<strong class="lb iu">学生年龄</strong>和<strong class="lb iu">错误消息</strong>。配合使用<strong class="lb iu"> super()。_ _ init _ _(self . error _ message)</strong>，我们实例化了基类<strong class="lb iu"> Exception </strong>，参数帮助我们显示错误消息。</p><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi nt"><img src="../Images/adf65e14319bc3e92a5299b2c28a4a06.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*rC3f90aAgcV0I9za"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk translated">照片由<a class="ae ky" href="https://unsplash.com/@mundane?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Serenity Mitchell </a>在<a class="ae ky" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄</p></figure><h1 id="01e5" class="mw mp it bd mx my mz na nb nc nd ne nf jz ng ka nh kc ni kd nj kf nk kg nl nm bi translated">关键要点</h1><ul class=""><li id="82c0" class="lv lw it lb b lc nn lf no li nu lm nv lq nw lu ma mb mc md bi translated">我们必须消除<strong class="lb iu">语法错误</strong>来运行我们的 Python 代码，而<strong class="lb iu">异常</strong>可以在运行时处理。</li><li id="eedc" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">我们可以用<strong class="lb iu"> try-except </strong>块捕捉并处理异常。</li><li id="09f1" class="lv lw it lb b lc me lf mf li mg lm mh lq mi lu ma mb mc md bi translated">如果我们希望对特定条件下发生的事情有更多的控制，我们可以定义自己的异常类型。</li></ul><h1 id="3ec0" class="mw mp it bd mx my mz na nb nc nd ne nf jz ng ka nh kc ni kd nj kf nk kg nl nm bi translated">结论</h1><p id="b992" class="pw-post-body-paragraph kz la it lb b lc nn ju le lf no jx lh li np lk ll lm nq lo lp lq nr ls lt lu im bi translated">在这篇文章中，我解释了在 Python 中<strong class="lb iu">错误和异常处理的基础。</strong></p><p id="abb7" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">这篇文章中的代码可以在<a class="ae ky" href="https://github.com/eisbilen/ExceptionHandling" rel="noopener ugc nofollow" target="_blank">我的 GitHub 库中找到。</a></p><p id="f3de" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">我希望这篇文章对你有用。</p><p id="872f" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">感谢您的阅读！</p></div></div>    
</body>
</html>