<html>
<head>
<title>Do Not Abuse Try Except In Python</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">除非在 Python 中，否则不要滥用 Try</h1>
<blockquote>原文：<a href="https://towardsdatascience.com/do-not-abuse-try-except-in-python-d9b8ee59e23b?source=collection_archive---------4-----------------------#2020-08-10">https://towardsdatascience.com/do-not-abuse-try-except-in-python-d9b8ee59e23b?source=collection_archive---------4-----------------------#2020-08-10</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><figure class="is it gp gr iu iv gh gi paragraph-image"><div role="button" tabindex="0" class="iw ix di iy bf iz"><div class="gh gi ir"><img src="../Images/1ca7473aa6ce00d0801f9f6e5626f1e6.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*BFqQgVgGx5Lc_FfLXsrzNw.jpeg"/></div></div><p class="jc jd gj gh gi je jf bd b be z dk translated"><a class="ae jg" href="https://pixabay.com/users/Quangpraha-7201644/" rel="noopener ugc nofollow" target="_blank">光婆罗</a>在<a class="ae jg" href="https://pixabay.com/photos/fish-fishermen-fishing-net-fishing-3062034/" rel="noopener ugc nofollow" target="_blank"> Pixabay </a>上的照片</p></figure><div class=""/><div class=""><h2 id="f306" class="pw-subtitle-paragraph kg ji jj bd b kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx dk translated">试着除了有时会让你的生活变得困难</h2></div><p id="352a" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">像大多数其他编程语言一样，Python 支持在运行时捕获和处理异常。但是，有时候我发现它已经被过度使用了。</p><p id="6f38" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">原来有些开发者，尤其是 Python 新手，一旦发现这样的特性，就倾向于用 try …除了…很多。然而，我想说的是，如果可能的话，我们应该尽量避免使用它，尤其是在开发的早期阶段。你会发现，让问题显露出来，比隐藏起来更好。</p><p id="0465" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">在本文中，我将展示一些例子来说明“try … except …”如何产生问题，以及在 Python 编程中什么是更好的方式。</p><h1 id="f675" class="lu lv jj bd lw lx ly lz ma mb mc md me kp mf kq mg ks mh kt mi kv mj kw mk ml bi translated">问题定义</h1><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div role="button" tabindex="0" class="iw ix di iy bf iz"><div class="gh gi ir"><img src="../Images/92ad8c37b6edc753106cc0ebb0a4727b.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*chprYv6_rsyuSw6k4a9-1g.jpeg"/></div></div><p class="jc jd gj gh gi je jf bd b be z dk translated">照片由<a class="ae jg" href="https://pixabay.com/users/geralt-9301/" rel="noopener ugc nofollow" target="_blank"> geralt </a>在<a class="ae jg" href="https://pixabay.com/photos/definition-man-finger-touch-show-4255411/" rel="noopener ugc nofollow" target="_blank"> Pixabay </a>上拍摄</p></figure><p id="6cc3" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">先说一个有问题的例子，这是我见过的非常典型的场景。</p><pre class="mm mn mo mp gt mq mr ms mt aw mu bi"><span id="dd54" class="mv lv jj mr b gy mw mx l my mz">def f1(num):<br/>    try:<br/>        return (num+1)*2<br/>    except Exception as e:<br/>        print('Error: ', e)</span><span id="20d7" class="mv lv jj mr b gy na mx l my mz">def f2(num):<br/>    try:<br/>        return (num+1)*3<br/>    except Exception as e:<br/>        print('Error: ', e)</span><span id="6b29" class="mv lv jj mr b gy na mx l my mz">def f3(num):<br/>    try:<br/>        return (num+1)*4<br/>    except Exception as e:<br/>        print('Error: ', e)</span></pre><p id="e79a" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">我们有三个函数来做一些简单的数值计算。都是用 try 实现的…除了…用 everything。然后，我们希望在代码中使用它们，如下所示。</p><pre class="mm mn mo mp gt mq mr ms mt aw mu bi"><span id="6478" class="mv lv jj mr b gy mw mx l my mz">num1 = f1(5)<br/>num2 = f2('5')<br/>num3 = f3(5)</span></pre><p id="7b2b" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">请注意，我故意在第二个函数中传递了一个字符串“5”，因为我只是想人为地创建一个异常。我们得到的结果如下。</p><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div class="gh gi nb"><img src="../Images/e88927c16fcad3ae75c6a7044bb52ca7.png" data-original-src="https://miro.medium.com/v2/resize:fit:742/format:webp/1*D0ZjEa5GKR50JnWROMwN-Q.png"/></div></figure><p id="5738" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">这里我们只有几行代码。或许，意识到这个问题并不太难。然而，假设你正在做一个更大规模的项目，错误消息<code class="fe nc nd ne mr b">must be str, not int</code>对你定位问题没有太大帮助。</p><h1 id="3627" class="lu lv jj bd lw lx ly lz ma mb mc md me kp mf kq mg ks mh kt mi kv mj kw mk ml bi translated">另一个例子</h1><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div role="button" tabindex="0" class="iw ix di iy bf iz"><div class="gh gi ir"><img src="../Images/6900be24c71ceaeff41afcc79b817250.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*7FqbpSPgCsC7DFkE-arNxQ.jpeg"/></div></div><p class="jc jd gj gh gi je jf bd b be z dk translated">照片由<a class="ae jg" href="https://pixabay.com/users/guvo59-9285194/" rel="noopener ugc nofollow" target="_blank"> guvo59 </a>在<a class="ae jg" href="https://pixabay.com/photos/pc-computer-stethoscope-technology-3540378/" rel="noopener ugc nofollow" target="_blank"> Pixabay </a>上拍摄</p></figure><p id="14b2" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">我们能从异常对象<code class="fe nc nd ne mr b">e</code>中得到的错误信息有时非常有限。我认为在 Python 中这并不总是有意义的。事实上，前一个并不太坏，因为它至少告诉你为什么会发生错误。让我们看看这个。</p><pre class="mm mn mo mp gt mq mr ms mt aw mu bi"><span id="0fd9" class="mv lv jj mr b gy mw mx l my mz">def f4(key):<br/>    try:<br/>        d = {'a': 1, 'b': 2}<br/>        return d[key]<br/>    except Exception as e:<br/>        print('Error: ', e)</span><span id="36a9" class="mv lv jj mr b gy na mx l my mz">f4('c')</span></pre><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div class="gh gi nf"><img src="../Images/ff60eddc445e76eb3c51d91f05fc6b64.png" data-original-src="https://miro.medium.com/v2/resize:fit:744/format:webp/1*ACBE7wI4srfcrnZS7n7ZyA.png"/></div></figure><p id="9f97" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">当然，在这个例子中我们只有一行代码，我们知道什么是“c”。然而，同样，如果这发生在一个项目中，如果我们只得到一个错误消息“c ”,我们如何解决这个问题呢？</p><h1 id="bc50" class="lu lv jj bd lw lx ly lz ma mb mc md me kp mf kq mg ks mh kt mi kv mj kw mk ml bi translated">最坏的情况</h1><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div role="button" tabindex="0" class="iw ix di iy bf iz"><div class="gh gi ir"><img src="../Images/e798eb8c123a83791405b69f504c48ef.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*inNW9lHYb-7_yu5DvcNk6A.jpeg"/></div></div><p class="jc jd gj gh gi je jf bd b be z dk translated"><a class="ae jg" href="https://pixabay.com/users/Ramdlon-710044/" rel="noopener ugc nofollow" target="_blank">拉姆德隆</a>在<a class="ae jg" href="https://pixabay.com/photos/good-bad-opposite-choice-choose-1123013/" rel="noopener ugc nofollow" target="_blank">皮克斯贝</a>拍摄的照片</p></figure><p id="cfa8" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">你能想象情况还能更糟吗？嗯，这个问题可能与我们的主题不是 100%相关，但我只是想提出它，因为它可能会被后面部分的解决方案解决。</p><p id="ee6f" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">如果我们把所有的代码放在 try 块中，并在 except 块中捕获所有的一般异常，你认为这样会非常安全吗？答案是否定的，不然我大概会推荐到处用:)</p><p id="1f99" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">让我们看看这个例子。</p><pre class="mm mn mo mp gt mq mr ms mt aw mu bi"><span id="77e8" class="mv lv jj mr b gy mw mx l my mz">def f5(num):<br/>    try:<br/>        return num*3<br/>    except Exception as e:<br/>        print('Error: ', e)</span><span id="e423" class="mv lv jj mr b gy na mx l my mz">num = f5('5')<br/>print('Result is', num)</span></pre><p id="f318" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">同样，我们定义了一个非常简单的数值计算函数，并向其中传递一个字符串。我们可能期望“异常”会被捕获，但是没有异常。</p><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div class="gh gi ng"><img src="../Images/5c4211f3e915ce31cf843cbf4cd322fc.png" data-original-src="https://miro.medium.com/v2/resize:fit:706/format:webp/1*ylsG5TpAF16DNowDZ0zsSg.png"/></div></figure><p id="1266" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">Python 太灵活了，不会有错误:)</p><h1 id="fea5" class="lu lv jj bd lw lx ly lz ma mb mc md me kp mf kq mg ks mh kt mi kv mj kw mk ml bi translated">丑陋的解决方案:回溯库</h1><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div role="button" tabindex="0" class="iw ix di iy bf iz"><div class="gh gi ir"><img src="../Images/f7752a38c3362f58f925ab4f0e11fe81.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*rjiUBIMFsORdbzCFiRhWcA.jpeg"/></div></div><p class="jc jd gj gh gi je jf bd b be z dk translated">照片由<a class="ae jg" href="https://pixabay.com/users/geralt-9301/" rel="noopener ugc nofollow" target="_blank"> geralt </a>在<a class="ae jg" href="https://pixabay.com/photos/terrorist-terror-happiness-positive-2481808/" rel="noopener ugc nofollow" target="_blank"> Pixabay </a>上拍摄</p></figure><p id="eff9" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">如果想尝试所有代码并捕捉异常，可以使用 Python 内置的<code class="fe nc nd ne mr b">traceback</code>库。让我们使用如上所示的相同示例。</p><pre class="mm mn mo mp gt mq mr ms mt aw mu bi"><span id="a9a4" class="mv lv jj mr b gy mw mx l my mz">import traceback</span><span id="81be" class="mv lv jj mr b gy na mx l my mz">def f4(key):<br/>    try:<br/>        d = {'a': 1, 'b': 2}<br/>        return d[key]<br/>    except Exception as e:<br/>        e = traceback.format_exc()<br/>        print('Error: ', e)</span><span id="4a3e" class="mv lv jj mr b gy na mx l my mz">f4('c')</span></pre><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div class="gh gi nh"><img src="../Images/7016e1efb4f272ddd924ddb6b8cb8312.png" data-original-src="https://miro.medium.com/v2/resize:fit:1130/format:webp/1*vFSeqbZy08iQjDO0dwDQKw.png"/></div></figure><p id="3153" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">使用 traceback 帮助我们打印出关于错误的更多信息，因此我们可以更容易地解决问题。然而，我们需要导入一个额外的库并编写更多的代码来完成这个任务。</p><p id="aa53" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">只是需要再三考虑这样做是否值得？让我们看看其他的好习惯。</p><h1 id="4e05" class="lu lv jj bd lw lx ly lz ma mb mc md me kp mf kq mg ks mh kt mi kv mj kw mk ml bi translated">解决方案 0:不要抓它</h1><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div role="button" tabindex="0" class="iw ix di iy bf iz"><div class="gh gi ir"><img src="../Images/8a1a52d850730887aeff10ef1fef40ea.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*8ZH5BhFVylKGrRoXSEyGeA.jpeg"/></div></div><p class="jc jd gj gh gi je jf bd b be z dk translated">由<a class="ae jg" href="https://pixabay.com/users/lechenie-narkomanii-3764644/" rel="noopener ugc nofollow" target="_blank"> lechenie-narkomanii </a>在<a class="ae jg" href="https://pixabay.com/photos/freedom-sky-hands-handcuffs-clouds-1886402/" rel="noopener ugc nofollow" target="_blank"> Pixabay </a>上拍摄的照片</p></figure><p id="17c4" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">添加这一部分是为了防止有人会说这样的话:</p><blockquote class="ni nj nk"><p id="b9f0" class="ky kz nl la b lb lc kk ld le lf kn lg nm li lj lk nn lm ln lo no lq lr ls lt im bi translated">为什么使用 raise 或 assert？如果你根本不使用 try … except …的话，完整的回溯堆栈将会简单地显示出来！</p></blockquote><p id="51fb" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">的确，这也是我在这篇文章中想说的。正是对标题“不要滥用 try …除了…用 Python”的解决方案。我提供下面两个“解决方案”的原因只是想展示什么是好的方式。</p><h1 id="9dba" class="lu lv jj bd lw lx ly lz ma mb mc md me kp mf kq mg ks mh kt mi kv mj kw mk ml bi translated">解决方案 1:引发异常</h1><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div role="button" tabindex="0" class="iw ix di iy bf iz"><div class="gh gi ir"><img src="../Images/137760b92bef1756a58376a578536462.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*fZbpV1oCXPpZPoFIg-VZnw.jpeg"/></div></div><p class="jc jd gj gh gi je jf bd b be z dk translated">照片由<a class="ae jg" href="https://pixabay.com/users/Pezibear-526143/" rel="noopener ugc nofollow" target="_blank"> Pezibear </a>在<a class="ae jg" href="https://pixabay.com/photos/child-girl-water-stone-throw-541908/" rel="noopener ugc nofollow" target="_blank"> Pixabay </a>上拍摄</p></figure><p id="877a" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">正如我前面所说的，我们应该避免使用太多的 try … except …这样会隐藏异常。相反，我们希望尽可能多地揭示异常。使用<code class="fe nc nd ne mr b">raise</code>手动引发异常是一种很好的方式。</p><p id="c3ba" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">让我们修改我们的<code class="fe nc nd ne mr b">f1</code>、<code class="fe nc nd ne mr b">f2</code>和<code class="fe nc nd ne mr b">f3</code>函数。</p><pre class="mm mn mo mp gt mq mr ms mt aw mu bi"><span id="796c" class="mv lv jj mr b gy mw mx l my mz">INVALID_NUM_EXCEPTION = Exception('The parameter must be integer!')</span><span id="4f2c" class="mv lv jj mr b gy na mx l my mz">def f1(num):<br/>    if type(num) != int:<br/>        raise INVALID_NUM_EXCEPTION<br/>    return (num+1)*2</span><span id="8081" class="mv lv jj mr b gy na mx l my mz">def f2(num):<br/>    if type(num) != int:<br/>        raise INVALID_NUM_EXCEPTION<br/>    return (num+1)*2</span><span id="b2ff" class="mv lv jj mr b gy na mx l my mz">def f3(num):<br/>    if type(num) != int:<br/>        raise INVALID_NUM_EXCEPTION<br/>    return (num+1)*2</span></pre><p id="c6fb" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">这里，我们定义了一个异常，并在函数中当传入的参数类型不是整数时引发它。</p><p id="9040" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">然后，让我们运行相同的代码来使用这些函数。</p><pre class="mm mn mo mp gt mq mr ms mt aw mu bi"><span id="2269" class="mv lv jj mr b gy mw mx l my mz">num1 = f1(5)<br/>num2 = f2('5')<br/>num3 = f3(5)</span></pre><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div class="gh gi np"><img src="../Images/ff9840ea81c1a31933a4621d38a84a65.png" data-original-src="https://miro.medium.com/v2/resize:fit:1390/format:webp/1*fYqx1f0nBU5zJPFcR-d2tQ.png"/></div></figure><p id="7773" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">遇到一个错误并不太糟糕，如果它告诉你错误到底是什么，在哪里发生的。</p><h1 id="9c92" class="lu lv jj bd lw lx ly lz ma mb mc md me kp mf kq mg ks mh kt mi kv mj kw mk ml bi translated">解决方案 2:断言</h1><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div role="button" tabindex="0" class="iw ix di iy bf iz"><div class="gh gi ir"><img src="../Images/9046597bec4b89dbbab6784f4bf8c0c1.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*ovIMcB1ocs0teEL5QZKTkA.jpeg"/></div></div><p class="jc jd gj gh gi je jf bd b be z dk translated">照片由<a class="ae jg" href="https://pixabay.com/users/aitoff-388338/" rel="noopener ugc nofollow" target="_blank">艾托夫</a>在<a class="ae jg" href="https://pixabay.com/photos/bolt-padlock-lock-security-shed-1751089/" rel="noopener ugc nofollow" target="_blank"> Pixabay </a>上拍摄</p></figure><p id="bb7f" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">尽管断言在测试中更常用，但我们仍然可以在开发过程中使用它来确保我们的代码有更少的 bug。此外，如果我们不关心确切的异常类型，使用断言通常比引发异常更简洁。</p><pre class="mm mn mo mp gt mq mr ms mt aw mu bi"><span id="24f3" class="mv lv jj mr b gy mw mx l my mz">INVALID_NUM_MSG = 'The parameter must be integer!'</span><span id="a441" class="mv lv jj mr b gy na mx l my mz">def f1(num):<br/>    assert isinstance(num, int), INVALID_NUM_MSG<br/>    return (num+1)*2</span><span id="e9aa" class="mv lv jj mr b gy na mx l my mz">def f2(num):<br/>    assert isinstance(num, int), INVALID_NUM_MSG<br/>    return (num+1)*2</span><span id="1f95" class="mv lv jj mr b gy na mx l my mz">def f3(num):<br/>    assert isinstance(num, int), INVALID_NUM_MSG<br/>    return (num+1)*2</span></pre><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div role="button" tabindex="0" class="iw ix di iy bf iz"><div class="gh gi nq"><img src="../Images/0353586b2a164bc138c3af6a478536ec.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*vcOxZSUqshQrD43CMt-Ayg.png"/></div></div></figure><h1 id="4631" class="lu lv jj bd lw lx ly lz ma mb mc md me kp mf kq mg ks mh kt mi kv mj kw mk ml bi translated">摘要</h1><figure class="mm mn mo mp gt iv gh gi paragraph-image"><div role="button" tabindex="0" class="iw ix di iy bf iz"><div class="gh gi ir"><img src="../Images/927b95fe59816e1629e79edd6f91eefe.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*kKsAVCCZZQYp7jXKG2XS0g.jpeg"/></div></div><p class="jc jd gj gh gi je jf bd b be z dk translated">照片由<a class="ae jg" href="https://pixabay.com/users/pasja1000-6355831/" rel="noopener ugc nofollow" target="_blank"> pasja1000 </a>在<a class="ae jg" href="https://pixabay.com/photos/dandelion-sphere-fluffy-plant-3347363/" rel="noopener ugc nofollow" target="_blank"> Pixabay </a>上拍摄</p></figure><p id="345d" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">在编程语言中知道更多的技巧是有益的。我不得不说，每当我知道一些很酷的东西，我也会倾向于使用它。然而，它也需要再三考虑我们是否需要这样做，以及这样做是否比设置障碍给我们带来更多的好处。</p><p id="4e5d" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">因此，不要将所有代码放在 Python 中的 try … except …块中。让错误显露出来，让我们的生活更轻松！</p><div class="is it gp gr iu nr"><a href="https://medium.com/@qiuyujx/membership" rel="noopener follow" target="_blank"><div class="ns ab fo"><div class="nt ab nu cl cj nv"><h2 class="bd jk gy z fp nw fr fs nx fu fw ji bi translated">通过我的推荐链接加入 Medium 克里斯托弗·陶</h2><div class="ny l"><h3 class="bd b gy z fp nw fr fs nx fu fw dk translated">作为一个媒体会员，你的会员费的一部分会给你阅读的作家，你可以完全接触到每一个故事…</h3></div><div class="nz l"><p class="bd b dl z fp nw fr fs nx fu fw dk translated">medium.com</p></div></div><div class="oa l"><div class="ob l oc od oe oa of ja nr"/></div></div></a></div><p id="7d6b" class="pw-post-body-paragraph ky kz jj la b lb lc kk ld le lf kn lg lh li lj lk ll lm ln lo lp lq lr ls lt im bi translated">如果你觉得我的文章有帮助，请考虑加入 Medium 会员来支持我和成千上万的其他作者！(点击上面的链接)</p></div></div>    
</body>
</html>